###服务启动端口号
server:
  port: 8200

###服务名称(服务注册到eureka名称)
spring:
    application:
        name: app-michael-weixin
    redis:
        host: 127.0.0.1
        port: 6379

###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka

###swagger相关配置
swagger:
  basePackage: com.michael.weixin.service
  title: 微服务电商-微信服务
  description: 微信服务api文档

###微信相关
logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
wx:
  mp:
    configs:
      - appId: wxee245bd735096372 #（一个公众号的appid）
        secret: 756432980cd2a6aeea5c1fc53ac50193 #（公众号的appsecret）
        token: michael #（接口配置里的Token值）

michael:
  weixin:
    registration:
       code:
       ###微信注册码消息
        message:  您的注册码为:%s，请关注<a href="https://www.baidu.com">测试连接</a>,感谢！
    ###默认提示消息
    default:
      registration:
        code:
          message: 您的消息，我们已经收到,会及时回复给您的!